version: "3"

services:
  api:
    build:
      context: ./api
    ports:
      - 8000:8000
    volumes:
      - ./api/app:/app
    env_file:
      - app.env
    command: >
      sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"

  front:
    build:
      context: ./front
    ports:
      - 3000:3000
    volumes:
      - ./front:/front

  #   environment:
  #     - DB_HOST=db
  #     - DB_NAME=recipe
  #     - DB_USER=postgres
  #     - DB_PASS=supersecretpassword
  #   depends_on:
  #     - db
  # db:
  #   image: "postgres:10-alpine"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=supersecretpassword
  #     - POSTGRES_DB=criptosentiment
