name: Docker Image CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -f dockerfiles/api/Dockerfile .
    - name: Test the api container
      run: docker-compose run api sh -c "python manage.py test && flake8"
