name: Docker Image CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose build
    - name: Test the api container
      run: ./compose.sh test
      shell: bash
